### ISSUE TITLE
pauses are mis-timed

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#14]
A number of the new pauses seem to be mis-timed, so that the message being displayed happens after the pause is finished.  Potion of Sleep, casting spells, teleport, death... I don't think it's my computer, although I'm willing to entertain the possibility.

**Comment by atsb** [comment]
NAPTIME in larncons.h was set to 1000 (1 second) the new posix nap function in sysdep.c waits for exactly the right amount from the integer time you set.  Before it was a bit off (and too fast).

I've reduced it to 500 (1/2 second).  What happens is that the message displays after an action happens due to the wait, it won't be as 'snappy' as before.

**Comment by hymie0** [comment]
I wonder if the problem is bufferring.  You print a statement

    lprcat ("\nYou fall asleep. . .");

then you

       nap (NAPTIME);

then you print the line feed

      lprcat ("\nYou woke up!");

which makes the text before it actually appear.  That is probably why I'm experiencing the weird lags.

**Comment by hymie0** [comment]
I've been adding lflush() to the end of some of the routines in io.c like lprc() and lprcat(), and that seems to be improving things.

**Comment by atsb** [comment]
I was not touching these because it is just pure mess everywhere.  I will make a reusable function to handle these bits.  It was never a problem until the posix sleep was implemented (because these were not made with posix in mind).  Currently my working trunk in GNU/Linux contains all kinds of things, once I push these to github a lot of these should be fixed.

**Comment by atsb** [comment]
Try now, should be helping a few things around the text and buffering.

**Comment by hymie0** [comment]
Much better.  Thanks.
