### ISSUE TITLE
14.0 Enhancements to Larn

### ISSUE THREAD

**Issue by atsb** [atsb/RL_M#26]
For anyone to comment and provide their thoughts, feelings and suggestions on / for enhancements to Larn.

1. Limited Colour Support - Menu, Text, Player and Keyword colouring.
    Which colours would you like to see?  Which ones would be the nicest to look at?

2. Enhancements to support increased modding capability - Right now, you really have to recompile to change anything.  What would you like to have initially available to change without having to recompile?  This functionality will be done by embedding Lua (I hate fat embedded languages).

3. Additional items, spells, monsters etc.. - What would you like to see?

-Gibbon

**Comment by hymie0** [comment]
A few opening thoughts.  I'm sure I'll have more later.

1. Please consider 2 color schemes, for black-text-on-white-background terminals and for white-text-on-black-background terminals.  I like white background, and I like red, blue, magenta and HATE green, cyan, and yellow.  The opposite is probably true for people who like black background.

Please add color to items on the screen.  Sometimes I can't see the fortune cookies (not that big of a deal) or the altars (pretty big deal sometimes).  Having those stand out -- even just in bold -- would be very nice.

2.  I don't know much lua, but I've seen it in Dungeon Crawl Stone Soup.  Other than color and maybe a default character name, I can't think of much user-level configuration needed.

3. I'm embarrassed to ask this, but what the hell.  In one of the other larn forks, there was an item  that gave you long-term expanded awareness.  EA is my favorite character enhancement, but as an item, it's IMHO a bit too powerful.  I have a personal patch that makes the Sword of Hymie give you half-expanded awareness (2 spaces instead of 3) as long as the sword has a non-negative enchantment (watch out for disenchantress).

On the other hand, please be careful with adding too much stuff.  Part of the charm of Larn (IMHO) is its simplicity.  If I wanted a pet and a bunch of side quests, I'd go play Nethack.

**Comment by atsb** [comment]
> 1. Please consider 2 color schemes, for black-text-on-white-background terminals and for white-text-on-black-background terminals. I like white background, and I like red, blue, magenta and HATE green, cyan, and yellow. The opposite is probably true for people who like black background.

I will consider it.  I could code a little config file utility to read 'WhiteTerm' and 'BlackTerm' from a flat text file and when defined will set the colours accordingly.  I will set some items to a colour, not all of them as I think it results in visual vomit with too many colours, that's not a problem.

> I don't know much lua, but I've seen it in Dungeon Crawl Stone Soup. Other than color and maybe a default character name, I can't think of much user-level configuration needed.

Yeah, Lua was at the extreme end, much of this can be in a simple config file.

> 
On the other hand, please be careful with adding too much stuff. Part of the charm of Larn (IMHO) is its simplicity. If I wanted a pet and a bunch of side quests, I'd go play Nethack.

No worries about this, I also hate software bloat.  I'm only proposing some of these things as when 14.0 is released 'no' new additions will be in Larn (apart from feature requests that aren't too game-changing).  I'm trying to get a good balance between modernising it a little and keeping that charm :)

As always, great feedback!

**Comment by atsb** [comment]
UPDATE:

![larn_win32](https://cloud.githubusercontent.com/assets/8221424/17347237/ff5aa8f8-590e-11e6-86dc-153ae9ca2137.jpg)

For 14.0 (it might be a little delayed) I've ported the codebase to Visual Studio (Community 2015).  It builds somewhat cleanly using Visual C++ and I'm also linking against PDCurses Win32a variant to get a real window.  I'm giving Windows users some much needed love, since mostly everything is only tested on *nix platforms.

And yes, I am aware of the TDM-GCC mass-warnings on Windows.

**Comment by atsb** [comment]
Terminal colors for Black and White terminals is done (compile flag).  I'll be testing it more in-depth tonight to get a good balance of readability and colors which work well together.

**Comment by hymie0** [comment]
I'm not very familiar with CMake.  How do I unset the TERM_DARK_BACKGROUND
flag?  I ended up running cmake and editing the file
CMakeFiles/larn.dir/flags.make , but is this the "correct" way to do it?

--hymie!

**Comment by atsb** [comment]
You can edit the CMakeLists file in the build directory and remove the flag in DEBUG and RELEASE builds.  It is done so only 1 flag needs to be set.  If this is not set then it will compile using the lighter colors for the terminal.  Perhaps it would be better if I added a few extra build options for DEBUG_LIGHT_TERM, DEBUG_DARK_TERM etc...

**Comment by atsb** [comment]
Since I will be reimplementing the mazefile.  I'll add in a special custom maze for 14.0 since 2016 will be 30 years from Larn's initial release by Noah.

I think it will be a nice touch.

**Comment by atsb** [comment]
Closing as all 14.0 additions are done, final commit of the mazefile will be done later and then the final 14.0 release.
