### ISSUE TITLE
redraw screen on teleport trap

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#27]
I was wandering the dungeon today and I stepped on a teleport trap.  It teleported me to another location on the same level (1), but did not draw the ^ in the spot where the teleport trap was.  I could stand next to it and hit the ^ command and it would say "teleport trap" but there was no ^ on the screen.

Pressing ^L forced a redraw and the teleport trap appeared.

**Comment by hymie0** [comment]
Not sure if this is relevant, but the full floor was already visible thanks to a magic mapping scroll.  Maybe some flag got tripped that prevented a screen draw?

**Comment by atsb** [comment]
Simple fix.  I'll force a screen refresh when you teleport.  Similar to opening a door, the whole screen redraws so you can see the open door.  I'll push it in with the next trunk update.

**Comment by atsb** [comment]
I'll be adding this along with the fix for my game breaking bug :) 

I think you're right about the scroll, same thing happens with WIZARD mode, it's invisible.  I'll do the following:

1. When using wizard mode, when entering a level, and when using the scroll, I'll do a full refresh of the screen.

**Comment by atsb** [comment]
Should be fixed now, I saw one when I was a wizard.  Added some refresh(); calls to stairs (up and down), magic mapping scrolls too.
