### ISSUE TITLE
feedback when buying from the store

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#4]
I don't know if I'd call this an "issue", more of a "feature request".

When I buy things from the store, there isn't any real obvious feedback.  My available gold decreases, but if I'm not sure what it was, then I won't know how much it's gone down.

**Comment by atsb** [comment]
I will refactor the ui to allow this.  Sounds like a nice feature.

**Comment by hymie0** [comment]
It looks like the older larn would use the "You picked up" routine on the bottom two lines under the screen.  You may not have enough room anymore, because I think the store is bigger.  But it was nice, because it showed the new item's inventory location, and the message sat there for about a second before clearing.

**Comment by atsb** [comment]
Latest push for store.c now shows current gold and updates the values when selling items.

**Comment by atsb** [comment]
I will implement something similar for store.

**Comment by atsb** [comment]
Buying from the store had the functionality but my changes to usleep made it appear too quickly.  Now Linux/Mac use a usleep(x * 500) instead of the * 1000 as a trade off (it feels more responsive).  After buying items, it will appear for about 1 second before vanishing.

I need to refactor the sleep as right now it is a bit of a mess.
