### ISSUE TITLE
save games

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#44]
Please don't remove the save-game feature entirely.  Sometimes I only have 10 or 15 minutes, and I can't play a full game, but I can at least progress a level or two.  I think I would really hate a game that I can't start and suspend, only start and either finish or quit entirely.

I agree about save files and cheaters.   There might be other ways to tell if the save-game file has been adjusted ... saving the expected time-stamp of the file inside the file comes to mind (although I'm sure it's still defeat-able).  I'm sure there are others.

**Comment by atsb** [comment]
Saved games **may** be removed in Larn-NEXT, it depends on how refactoring goes and where I want to make either improvements or simplifications.  Larn-SNAPSHOT will not change and it is being kept for bugfixes only now.  Anyone who only wants the original Larn won't bother with Larn-Next I assume, because it is going to be a little different.
