### ISSUE TITLE
larn-NEXT new dungeon every time I enter

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#45]
I don't know if this is a bug, or part of your vision of "the new Larn"

I enter the dungeon, I wander around a bit, come back to the town, and go back to the dungeon.  The dungeon is brand new.  Not only do I not know anything, but the dungeon itself is different.

**Comment by atsb** [comment]
This is a feature :) I believe it's in the changelog.  It's also part of why you currently cannot save / load.  I'm rewriting this so the maze won't be saved but your stats, items etc will be, otherwise the game will crash as the maze isn't stored in memory anymore.  It also prevents save-scumming and makes the end-game part a little more difficult as you'll need to save those scrolls!

**Comment by hymie0** [comment]
You're right.  It's there and I missed it. :(
