### ISSUE TITLE
Larn-NEXT: segfault when going to level 3 in wizard mode

### ISSUE THREAD

**Issue by christianpohlmann** [atsb/RL_M#58]
When in wizard mode, descending to level 3 leads to a segfault. The same thing happens when dumping the diagnosis file (wizard mode with EXTRA flag enabled and pressing ^A during the game).

**Comment by atsb** [comment]
Thanks for the bug!  I kinda knew what it was anyway.  I still was using the 'K' char at the top of the mazefile but only had 2 mazes (due to the size increase I have to modify all of them).  I thought it was just skip the blanks but it was segfaulting due to it actually requiring data within these boundaries.  I've copy/pasted the LARN30 map so it is within the boundaries of the algorithm which generates the mazes.

I've attached a picture to prove it :)
![larn_lv3](https://cloud.githubusercontent.com/assets/8221424/24598636/b3f168f4-184c-11e7-80d8-8330cd9f7d1b.PNG)

As for the diagnostics file, maybe you haven't seen but I've removed a good chunk of the EXTRA flags from the code as I'm refactoring it I don't see the use of diagnostics files, they serve no purpose for the enjoyment of Larn so it is actually broken because of this.

I've committed the mazefile fix so you can try again and it should be ok and not segfault anymore.  Thanks for the contribution, I appreciate it.

**Comment by christianpohlmann** [comment]
Thanks for the quick reply! It works correctly now on upstream.
I also merged your fix into my fork. Currently it does not compile, because I am refactoring the IO functions.
