### ISSUE TITLE
Right edge of the map

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#66]
The right edge of the map is not drawing properly:

```
                                                   Spells:  1( 1)
                                                   Level: 1
                                                   HP:  10( 10)
                                                   STR: 12   INT: 12   WIS: 12
                                                   CON: 12   DEX: 12   CHA: 12
                                                   ACC: 2    WCL: 3
                                                   Cave Level: 1
                                                   Gold: 72
                                                   Exp: 9
                                              ##          novice explorer
              #                       ....... ..
                                    ............
                                    ...........@
                                    #...........
                                #####.###.#H####
                                ........#.....#
                                #8#############
```

Even though there is nothing (visible) to my right, I cannot move right.  When I try, nothing happens -- that is, no time passes, so I assume there's supposed to be a wall or something there.  But it isn't drawing.  

I know you had experimented with 80-column-wide maps, so I'm not sure if the map should be scrolling, or if it ends there.

**Comment by atsb** [comment]
Yes I experimented but gameplay wasn't quite the same was it?  It took too long to navigate and you would run out of mobuls.  I set it to 48 due to the new status position but the maze code was biased towards the longer 68 char maps.  I improved it a little but I'll most likely have to totally rewrite the display stuff.  Though I don't want to finalise anything yet, we can experiment and see what fits Larn the best.

**Comment by hymie0** [comment]
You're switching to curses/ncurses, right?

In theory, curses can have scrolling windows.  You could have a "standard" 68-char-wide map, with a 48-char curses window, and when you get to (say) 2 or 5 or 10 steps from the edge, scroll the window (until it won't scroll anymore, then you have to start moving the character again).  The same should be true vertically as well.

Not sure I'm good enough to do that or show you how, but I'm pretty sure it's possible.

I like the new screen layout, by the way.  I haven't played enough to see the scroll/potion messages.

**Comment by atsb** [comment]
Good, I wasn't too fond of squashing everything at the bottom screen.  Yes it is possible, I thought maybe people might not like it as not many roguelikes do this, but yes I can do that.

**Comment by atsb** [comment]
I've been hacking on the terminal/io code for a few weeks now in my local copy (still in C, long story).  You think I've gone too far?

file:///home/atsb/Pictures/test.png

Removing the floor tiles was just a test to see how it would look.  It won't be possible to merge it yet.

**Comment by atsb** [comment]
I am slowly rewriting the io and terminal output to be fully conforming to curses routines instead of the dirty hacks that have been done to Larn (just see all the defines redeclaring nonsense specially for Larn).  Below is what I have in my local repo at home (this one is still written in C):

![test](https://cloud.githubusercontent.com/assets/8221424/26220187/eb559836-3c11-11e7-92c8-a233f025a95c.png)

I removed floor tiles as I thought it was a little distracting and properly implemented some nice color routines that were not hacks (this is why I removed them in master).  You think I've gone too far or you like it?  I've added back the 68 char maps and I thought adding the HP,WC etc stats on the right and the longer Exp, Gold etc.. along the bottom.  Instead of lprcat it is using waddr
 straight from curses.

**Comment by hymie0** [comment]
I really like the floor tiles.  I like knowing that I did or didn't visit the entire screen.  It would really annoy me if I missed one particular square on the map, and sitting in that one unvisited square was a Sword of Slashing.

**Comment by atsb** [comment]
![test](https://cloud.githubusercontent.com/assets/8221424/26222858/d516b618-3c1b-11e7-97b4-411189b340f9.png)

I've put the code back in, but due to my terminal changes I'll need to re-calculated their 'hidden' state until the player walks over them.  I'll probably be merging everything within a month.

**Comment by atsb** [comment]
Fixed in latest commit
