### ISSUE TITLE
In the bank, account summary isn't updated

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#7]
When I'm in the bank, I see two lines for "You have x gold pieces" and "You have x gold pieces in the bank".  When I deposit or withdraw money, these lines are not updated until I leave the bank and re-enter.

I forgot to check if these lines get updated when I sell gems.  When I next find a gem, I'll check.

And I wasn't going to open an "issue" for this, but as long as I'm here, GCC 4.7.1 has a warning

```
ansiterm.c: In function 'ansiterm_putchar':
ansiterm.c:404:14: warning: variable 'x' set but not used [-Wunused-but-set-variable]

```
which GCC 4.4.4 does not report.

**Comment by hymie0** [comment]
No, when I sell a gem, the "You have x gold pieces" line does not update.

**Comment by atsb** [comment]
Fixed in latest commit to the repo.  I don't build Larn on older GCC version.

I'll look into the GCC issue.

**Comment by atsb** [comment]
The GCC issue is likely due to GCC 4.4.4's age.  I won't bother getting into specifics about them but 4.4.4 is pretty old and perhaps the bug got past in the older versions.  I see this warning when building the binaries on Crux GNU/Linux (GCC 4.8.3), DragonFlyBSD (GCC 5) and Windows (TDM-GCC 5.1).  Clang on OSX does not report this bug either.

It will be fixed, I've been ignoring it as more important bugs were in-need of fixing.  It won't affect any game play though, it's set but not used so I'll sort that out.

Thanks for the efforts in your bug reports, I appreciate it.

**Comment by hymie0** [comment]
Maybe I wrote it backwards.

I see the warning in GCC 4.7.1 , which is the newest version I currently
have access to.

It's just a warning.  I only mention it because your recent changelog
referred to cleaning up old warnings.

--hymie!

**Comment by atsb** [comment]
Yep, makes sense.  Cleaning them up is a pain as some compilers don't show some or show different ones.  Eventually it should be warning-free on all platforms :)

**Comment by atsb** [comment]
Not updating in Bank is now fixed.  I will close the bug.  If it still happens, feel free to raise another.
