### ISSUE TITLE
great to see Larn back for FLOSS POSIX-based OSes, but make & install process could be improved?

### ISSUE THREAD

**Issue by dchmelik** [atsb/RL_M#74]
It's great to see Larn back for Free/Libre/Opensource Software POSIX-based OSes, and it compiled and ran fine on Slackware64 14.2 (a GNU/Linux) However, as someone who maintains an unofficial package based on an unofficial port ([larn-linux on Github](https://github.com/Nebula-Mechanica/larn-linux/),) I'd like to see the official port maybe do some things larn-linux does, but better, i.e., it has a ‘make install’ process (and should have ‘make uninstall’,) and a ‘wrapper script’ (as larn has directories so can't just be installed in /usr/games without a link,) but they unfortunately didn't make a link to the script and people instead had to run larn.sh (the wrapper.) The standard way to use wrapper scripts like that is install them in the game directory, then make a link such as: /usr/games/larn -> /usr/share/games/larn/larn.sh

**Comment by atsb** [comment]
Thanks for the compliment :) it also runs fine on PPC, MIPS, ARM (small and big endian) etc..  I've made the code incredibly portable.

There are 2 reasons why I have refused in making traditional GNU/Linux installation scripts.

1. The game also runs on Windows and while I could wrap up the files in ifdefs, I would rather leave it as a 'portable' game without thinking about how people will install it.

2. The game isn't packaged for any GNU/Linux distribution (not this original version anyway) and so there is no pressure to conform to installing.

Right now there are a ton of changes happening (and will happen) including the rewrite to Apache 2.0 perhaps after that, we can think about packaging it, because Larn isn't open-source or free-software due to Noah's not-for-profit clause and (in all versions except this) has the tgoto code under a proprietary license.  Once the Apache 2.0 code is done, that would be a good time :)

**Comment by atsb** [comment]
Just had a think about this actually.  We could, instead of placing all the files into the filesystem, we could instead place a .larn folder into the users home directory or inside .config, just like firefox, gedit etc do.  That way we just have to think about the binary location and some ifdefs for UNIX/Windows..

It would make packaging it for distro's much less painful.

**Comment by dchmelik** [comment]
That sounds good, at least for multiuser computers, which are still around, though personally doesn't matter to me.  As for my original comment, actually it's not a big deal either.  I was just thinking about it after changing from the unofficial port to official source code, when one of the people running  SlackBuilds.org was displeased I had removed their changes from the wrapper script, as I didn't use it, as it's not in your source code... but, if improved, may be worth adding.
