### ISSUE TITLE
no number pad movement?

### ISSUE THREAD

**Issue by dchmelik** [atsb/RL_M#75]
I thought the old Larn on DOS (I played in mid-to-late 1990s) let you use the number pad for movement... why not the Larn for current POSIX-based OSes such as GNU/Linux?

**Comment by atsb** [comment]
Because I backported a lot of original code from the 12.0 version from 1986 which was coded on an 80's terminal keyboard which lacked numpad's.

I'll be pushing my local copy in about 3 weeks which will contain this feature.

**Comment by atsb** [comment]
So I decided not to do this at all.  The reason:

NCurses doesn't have a nice way to deal with the numpad.  The older Larn 12.3 did it because that wasn't written with NCurses but used the native GNU/Linux API.  I had it with a whole bunch of escape codes but it worked on some keyboards and not on others, so I scrapped it altogether.

Just use the modern keys :)
