### ISSUE TITLE
screen oddities

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#78]
Just a couple of screen oddities that didn't warrant having separate issues.

EXP: followed by a 9-wide field wraps over the end of the screen into the far left column of the next line.

Scroll effects (such as "undead protection") are still drawn over the map.

Stats are not redrawn after an inventory display.

**Comment by atsb** [comment]
The EXP field looks ok on my terminal.  I actually held-down the wizard key just to see and it never overlapped.  I'm using just the default GNOME3 terminal at it's default size (80x24) I think.  Is your terminal smaller?  It could cause issues if it is.

**Comment by atsb** [comment]
Just glossed over my merges again with non-tired coffee-filled eyes :)

It seems I am forgetting to also correctly recalculate the maze generation in the other functions it is using.  I didn't touch the other generations for troom etc as I thought (wildly assumed) it wouldn't be affected.  It seems somewhere in eat, while it carves out the maze when a new one is generated that it was calculating where the player x and y was and generating the dungeon entrance at that point.  Since I merged my changes I'm basically blitzing this calculation as I thought it was handled by makemaze.

I'm hoping to one-day templatize the entire thing so we can have one function which is reused (overloaded) in different ways to handle the different maze generations.

I'm finding the best way of 'fixing' this crusty code is to simply remove functionality, see where it's failing and then fill the void with my change.  This is why it took 3 weeks for 16 changes :)

**Comment by atsb** [comment]
Should be fixed now

**Comment by hymie0** [comment]
Regarding EXP .. I'm using a standard 80x24 window as far as I can tell.

Looking at display.cpp I see this:

```
            cursor(69, 10);
            lprintf("EXP:");
            cursor(73, 10);
            lprintf("%-9d",(int)cdesc[EXPERIENCE]);
```

9 characters starting at 73 ends at 81.

I don't have GNOME terminal to check.

**Comment by atsb** [comment]
So what we can do is shift around the UI so the longer stats are towards the left.

**Comment by atsb** [comment]
Shifted EXP to be under the cave level along with LVL (player level).  I've replaced the old bot_data calculation for it's position with a hardcoded cursor position (53,19) so it is under the classname and gives enough space.  The old calculation was once again, hardcoded to be stuck at the far end with not enough space.
