### ISSUE TITLE
max inventory count in the store

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#81]
I am on the Town level, carrying as many items as I can.

I go into the bank and sell two gems.  Then I go to the store.  I buy one item.  When I try to buy the second item, I get a message that I cannot carry any more items.

I go outside the store and drop one item.  I go into the store and buy one item.  Then I go back outside the store and pick up my one item that I dropped.

Something in the store is mis-counting my items and preventing me from purchasing.

(I know you said that inventory is still a mess, and indeed, every now and then I will go into the bank and have one or two Eyes of Larn to sell.  So perhaps this is just a side-effect of that problem...)

**Comment by atsb** [comment]
I have a feeling there is more hardcoded math that is preventing it.  Since I reduced the max inventory size I've been running into all kinds of bad code which expects a very specific inventory size, very bad coding practice from past maintainers.  I'll have a look tonight while getting rid of all the casting going on too.

**Comment by atsb** [comment]
I've rewritten the inventory system, should be much better now.

Also fixed a bug where a stolen item wouldn't match the inventory, due to previously said hardcoded math 👍

**Comment by atsb** [comment]
Should be fixed
