### ISSUE TITLE
Potion of / Scroll of

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#89]
This might be an after-effect of the other issue where enchantments weren't being shown in the inventory.  Now I'm seeing all of my unidentified scrolls/potions as

```
c) a magic scroll of 
d) a magic potion of 
e) a magic scroll of 
g) a magic scroll of 
h) a magic scroll of 
i) a magic potion of 
```

**Comment by atsb** [comment]
This is fixed in my local repo (not yet pushed) as it's part of merge part 4 which will be pushed soon.

It was because the old code was doing fancy stuff identifying whether or not it needed the 'of'.  So I removed it and changed all the names in data.cpp to start with 'of'.  Because if you have not identified them yet those names are not shown, just 'magic scroll' etc..  Another easy fix for really stupid, overcomplicating functionality.

**Comment by atsb** [comment]
Fixed in latest merge push

**Comment by hymie0** [comment]
Almost fixed. :)

The "of" has moved to the "found to date" page.

```
The magic scrolls you have found to date are:

of enchant armor          of expanded awareness     of remove curse           

The magic potions you have found to date are:

of cure dianthroritis     
```

**Comment by atsb** [comment]
There's always another place where hardcodes are used :)

I'll add in strings for 'magic scroll' and 'magic potion'.
